---
permalink: online-help/concept-security-dashboard.html 
sidebar: sidebar 
keywords:  
summary: '您可以在Active IQ Unified Manager 信息板上启用或禁用"安全"面板。启用后、您还可以自定义合规性监控以及相关安全事件和管理操作的设置。' 
---
= 安全信息板
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在Active IQ Unified Manager 信息板上启用或禁用"安全"面板。启用后、您还可以自定义合规性监控以及相关安全事件和管理操作的设置。

[NOTE]
====
只有具有管理员角色的用户才能编辑这些设置。

====
系统会根据《适用于ONTAP 9的NetApp安全加固指南》中定义的建议评估ONTAP 集群、Storage VM和卷的安全标准。信息板上的安全面板可显示集群、Storage VM和卷的安全合规状态。启用此功能还会为存在安全违规的任何集群或Storage VM生成安全事件。



== 自定义设置

启用此功能后、您可以根据ONTAP 环境的具体情况自定义合规性监控设置。这些设置将触发相关的安全事件和管理操作。请按照以下步骤操作：

. 单击*自定义*。此时将显示"Customize Security Dashboard Settings"弹出窗口。
. 要启用或禁用ONTAP 集群的自定义设置、请展开集群的*常规设置*选项。有关用于自定义集群合规性的选项的信息，请参见 link:reference-cluster-compliance-categories.adoc["*集群合规性类别*"]。
. 要启用或禁用Storage VM的自定义设置、请展开Storage VM的*常规设置*选项。有关用于自定义 Storage VM 合规性的选项的信息，请参见 link:reference-svm-compliance-categories.adoc["Storage VM 合规性类别"]。
. 您还可以指定是否使用HTTPS传输从ONTAP 发送AutoSupport 消息。
. 如果启用身份验证设置、则Unified Manager会为默认ONTAP 管理员用户发出警报。

