---
permalink: online-help/reference-dashboard-page.html 
sidebar: sidebar 
keywords:  
summary: '信息板页面包含一些 " 面板 " ，用于显示所监控集群的容量，性能和安全运行状况概貌。此页面还提供了一个管理操作面板，其中列出了 Unified Manager 可用来解决某些事件的修复程序。' 
---
= 信息板页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
信息板页面包含"`panels`"、可显示所监控集群的容量、性能和安全运行状况概貌。此页面还提供了一个管理操作面板，其中列出了 Unified Manager 可用来解决某些事件的修复程序。

大多数面板还会显示该类别中的活动事件数量以及过去 24 小时内添加的新事件数量。此信息有助于您确定可能需要进一步分析哪些集群才能解决事件。单击这些事件将显示排名靠前的事件，并提供指向经过筛选以显示该类别中活动事件的事件管理清单页面的链接。

在信息板顶部、您可以选择这些面板是显示所有受监控集群的信息("`所有集群`")还是显示单个集群的信息。您可以先查看所有集群的状态，然后在需要查看详细信息时深入查看各个集群。

[NOTE]
====
根据您的配置，以下列出的某些面板不会显示在页面上。

====
* * 管理操作面板 *
+
Unified Manager 可以全面诊断某些问题并提供单一解决方案。如果可用，这些解决方法将显示在此面板中，并显示 * 修复它 * 或 * 全部修复 * 按钮。您可以直接从 Unified Manager 修复这些问题，而不必使用 ONTAP 系统管理器或 ONTAP 命令行界面。要查看所有问题，请单击

+
请参见 link:concept-fixing-ontap-issues-directly-from-unified-manager.html["直接从 Unified Manager 修复 ONTAP 问题"] 有关详细信息 ...

* * 容量面板 *
+
在查看所有集群时，此面板会显示每个集群的已用物理容量（应用存储效率节省后）和物理可用容量（不包括潜在的存储效率节省），预计磁盘达到全满前的天数， 以及基于已配置的 ONTAP 存储效率设置的数据精简率。它还会列出任何已配置云层的已用容量。单击条形图可转到该集群的聚合清单页面。单击"`D到全满`"文本将显示一条消息、用于标识剩余容量天数最少的聚合；单击聚合名称可查看更多详细信息。

+
查看单个集群时，此面板会显示按本地层上的每个磁盘类型排序的数据聚合的已用物理容量和物理可用容量，以及云层的已用容量和物理可用容量。单击某个磁盘类型的条形图可转到使用该磁盘类型的卷的卷清单页面。

* * 性能容量面板 *
+
在查看所有集群时，此面板会显示每个集群的性能容量值（过去 1 小时的平均值）以及性能容量达到上限之前的天数（基于每日增长率）。单击条形图可转到该集群的节点清单页面。请注意，节点清单页面会显示过去 72 小时的平均性能容量。单击"`D到全满`"文本将显示一条消息、用于标识剩余性能容量天数最少的节点；单击节点名称可查看更多详细信息。

+
查看单个集群时，此面板会显示集群已用性能容量百分比，总 IOPS 和总吞吐量（ MB/ 秒）值，以及预计这三个指标中每个指标达到上限之前的天数。

* * 工作负载 IOPS 面板 *
+
查看单个集群时，此面板会显示当前在特定 IOPS 范围内运行的工作负载总数，并在将光标悬停在图表上时指示每个磁盘类型的数量。

* * 工作负载性能面板 *
+
此面板显示分配给每个性能服务级别（ PSL ）策略的遵从和不遵从工作负载总数。它还会显示未分配 PSL 的工作负载数量。单击条形图可转到 " 工作负载 " 页面中分配给该策略的符合性工作负载。单击条形图后面的数字可转到分配给该策略的遵从和不遵从工作负载。

* * 安全面板 *
+
在查看所有集群时，此面板会显示合规和不合规的集群数量，合规和不合规的 Storage VM 数量以及加密和未加密的卷数量。合规性基于 http://["《适用于 ONTAP 9 的 NetApp 安全加固指南》"]。单击面板顶部的右箭头可在安全性页面中查看所有集群的安全详细信息。

+
查看单个集群时，此面板会显示集群是否合规，合规和不合规的 Storage VM 数量以及加密和未加密的卷数量。单击面板顶部的右箭头可在安全性页面中查看集群的安全详细信息。

* * 使用情况概述面板 *
+
查看所有集群时，您可以选择按最高 IOPS ，最高吞吐量（ MB/ 秒）或最高已用物理容量对集群进行排序。

+
查看单个集群时，您可以选择按最高 IOPS ，最高吞吐量（ MB/ 秒）或最高已用逻辑容量排序的工作负载。


