---
permalink: online-help/reference-volume-thresholds-page.html 
sidebar: sidebar 
keywords:  
summary: '"卷阈值"页面可用于为受监控卷配置全局运行状况阈值。您可以为单个卷或全局所有卷设置阈值。在全局配置选项时、所有对象的默认值都将被修改。但是，如果在对象级别更改了默认值，则不会修改全局值。' 
---
= 卷阈值页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"卷阈值"页面可用于为受监控卷配置全局运行状况阈值。您可以为单个卷或全局所有卷设置阈值。在全局配置选项时、所有对象的默认值都将被修改。但是，如果在对象级别更改了默认值，则不会修改全局值。

您必须具有应用程序管理员或存储管理员角色。

违反阈值时会生成事件。您可以对此类事件采取更正操作。

您可以为以下项设置阈值：容量、卷Snapshot副本、qtree配额、卷增长和索引节点。



== 容量区域

"容量"区域用于设置以下卷容量阈值条件。请注意，在卷上启用自动增长时，根据自动增长设置的最大卷大小（而不是原始卷大小），容量阈值被视为已违反。

* *空间接近全满*
+
指定将卷视为接近全满时的百分比：

+
** 默认值：80%
+
此阈值必须低于卷全满阈值、才能使管理服务器生成事件。

** 生成的事件：卷接近全满
** 事件严重性：警告


* *空间已满*
+
指定将卷视为全满时的百分比：

+
** 默认值：90%
** 生成的事件：卷已满
** 事件严重性：错误


* *达到全满前的天数*
+
指定在卷容量达到全满前的剩余天数：

+
** 默认值：15 (这也是最小值)
** 生成的事件：卷达到全满前的天数
** 事件严重性：错误






== Snapshot副本区域

Snapshot副本区域用于为卷中的Snapshot副本设置以下阈值条件：

* * Snapshot预留已满*
+
指定将为Snapshot副本预留的空间视为已满时的百分比：

+
** 默认值：90%
** 生成的事件：卷Snapshot预留已满
** 事件严重性：错误


* *达到全满前的天数*
+
指定为Snapshot副本预留的空间达到容量全满前的剩余天数：

+
** 默认值：7
** 生成的事件：卷Snapshot预留达到全满前的天数
** 事件严重性：错误


* *计数*
+
指定卷上被视为过多的Snapshot副本的数量：

+
** 默认值：1000
** 生成的事件：Snapshot副本太多
** 事件严重性：错误Unified Manager触发事件之前视为每个卷最大Snapshot副本数的Snapshot副本数低于ONTAP 最大值：




[cols="3*"]
|===
|  | ONTAP 最大值 | Unified Manager最大值 


 a| 
运行ONTAP 9.3或更早版本的FlexVol 卷以及运行ONTAP 9.7或更早版本的FlexGroup 卷
 a| 
255-255
 a| 
250



 a| 
运行ONTAP 9.4或更高版本的FlexVol 卷以及运行ONTAP 9.8或更高版本的FlexGroup 卷
 a| 
1023
 a| 
1000

|===


== qtree配额区域

使用qtree配额区域可以设置以下卷配额阈值条件：

* *接近过量提交*
+
指定根据qtree配额将卷视为接近过量使用时的百分比：

+
** 默认值：95%
** 生成的事件：卷qtree配额接近过量提交
** 事件严重性：警告


* *过量提交*
+
指定根据qtree配额将卷视为过量使用时的百分比：

+
** 默认值：100%
** 生成的事件：卷qtree配额已过量提交
** 事件严重性：错误






== 增长区域

"增长"区域用于为卷增长设置以下阈值条件：

* *增长率*
+
指定在系统生成卷增长率异常事件之前将卷的增长率视为正常的百分比：

+
** 默认值：1%
** 生成的事件：卷增长率异常
** 事件严重性：警告


* *增长率敏感度*
+
指定应用于卷增长率标准偏差的因子。如果增长率超过因子标准偏差、则会生成"卷增长率异常"事件。

+
增长率敏感度值越低、表示卷对增长率的变化非常敏感。增长率敏感度的范围为1到5。

+
** 默认值：2


+
[NOTE]
====
如果在全局阈值级别修改卷的增长率敏感度、则此更改也会应用于全局阈值级别聚合的增长率敏感度。

====




== 索引节点区域

通过索引节点区域、您可以为索引节点设置以下阈值条件：

* *接近全满*
+
指定将卷视为已占用其大部分索引节点的百分比：

+
** 默认值：80%
** 生成的事件：索引节点接近全满
** 事件严重性：警告


* *全满*
+
指定将卷视为已使用其所有索引节点时的百分比：

+
** 默认值：90%
** 生成的事件：索引节点已满
** 事件严重性：错误



