---
permalink: online-help/reference-cluster-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: '"容量：所有集群"视图中提供了以下字段、这些字段可在自定义视图和报告中使用。' 
---
= 集群容量字段
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"容量：所有集群"视图中提供了以下字段、这些字段可在自定义视图和报告中使用。

* *集群*
+
集群名称。您可以单击集群名称以导航到该集群的容量详细信息页面。

* *集群FQDN*
+
集群的完全限定域名(FQDN)。

* *高可用性对*
+
通过形成两个节点获得的HA对值。

* *总原始容量*
+
显示阵列中所有磁盘的总物理容量。

* *未配置原始容量*
+
容器类型不是聚合、损坏、备用或共享的磁盘的未配置容量。此容量始终高于ONTAP 中磁盘的物理容量。例如、假设磁盘为2 TB。在ONTAP 中、磁盘的物理容量为1.6 TB、而在Unified Manager中、未配置的原始容量为1.8 TB。

* *聚合总容量*
+
用户可用聚合的总大小。这包括Snapshot副本预留。

* *聚合已用容量*
+
聚合上已使用的容量。这包括卷、LUN和其他存储效率技术开销占用的容量。

* *聚合未用容量*
+
可用于在聚合上存储其他数据的容量。这包括Snapshot副本预留。

* *已用逻辑空间*
+
存储在此集群上的所有聚合上的数据的实际大小，而不会因使用 ONTAP 存储效率技术而节省空间。

* *数据缩减*
+
基于已配置的ONTAP 存储效率设置的数据精简率。

* *已分配LUN容量*
+
映射的LUN的容量。

* *未分配的LUN容量*
+
未映射到主机的所有LUN的容量。

* *卷总容量*
+
卷的总容量(已用+未用)。

* *卷已用容量*
+
卷的已用容量。

* *卷未使用容量*
+
卷的未使用容量。

* *卷保护容量*
+
已启用SnapMirror和SnapVault 的卷的容量。

* *已用云层(已许可)*
+
需要FabricPool 许可证的存储提供程序的云层中数据所使用的空间。

* *已用云层(其他)*
+
不需要FabricPool 许可证的StorageGRID 系统和ONTAP S3协议存储的云层中的数据所使用的空间。

* *型号/系列*
+
集群的型号或系列名称。

* *操作系统版本*
+
系统上安装的ONTAP 版本。

* * 联系人 *
+
集群的联系信息。

* * 位置 *
+
集群的位置。


