---
permalink: online-help/task-adding-space-to-the-data-directory-of-the-unified-manager-red-hat-enterprise-linux-host.html 
sidebar: sidebar 
keywords:  
summary: 如果在最初设置Linux主机并安装Unified Manager时为/opt/netapp/data目录分配的磁盘空间不足、无法支持Unified Manager、则可以在安装后通过增加/opt/netapp/data目录上的磁盘空间来添加磁盘空间。 
---
= 向 Linux 主机的数据目录添加空间
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
分配给的磁盘空间不足 `/opt/netapp/data` 目录以支持Unified Manager最初设置Linux主机并安装Unified Manager时、您可以在安装后通过增加上的磁盘空间来添加磁盘空间 `/opt/netapp/data` 目录。



== 开始之前

您必须对安装了 Unified Manager 的 Red Hat Enterprise Linux 或 CentOS Linux 计算机具有 root 用户访问权限。



== 关于此任务

建议您在增加数据目录大小之前备份 Unified Manager 数据库。



== 步骤

. 以 root 用户身份登录到要添加磁盘空间的 Linux 计算机。
. 按所示顺序停止 Unified Manager 服务和关联的 MySQL 软件： `systemctl stop ocieau ocie mysqld`
. 创建临时备份文件夹(例如、 `/backup-data`)、并具有足够的磁盘空间来容纳当前数据 `/opt/netapp/data` 目录。
. 复制现有的内容和权限配置 `/opt/netapp/data` 目录到备份数据目录： `cp -arp /opt/netapp/data/* /backup-data`
. 如果启用了 SE Linux ：
+
.. 为现有上的文件夹获取SE Linux类型 `/opt/netapp/data` 文件夹：
+
`se_type= ls -Z /opt/netapp/data | awk '{print $4}'| awk -F: '{print $3}'| head -1`

+
系统将返回类似于以下内容的确认消息：

+
[listing]
----
echo $se_type
mysqld_db_t
----
.. 运行 `chcon` 用于设置备份目录的SE Linux类型的命令： `chcon -R --type=mysqld_db_t /backup-data`


. 删除的内容 `/opt/netapp/data` 目录：
+
.. `cd /opt/netapp/data`
.. `rm -rf *`


. 扩展的大小 `/opt/netapp/data` 通过LVM命令或通过添加额外磁盘将目录设置为至少150 GB。
+
[NOTE]
====
如果已创建 `/opt/netapp/data` 然后、您不应尝试从磁盘挂载 `/opt/netapp/data` 作为NFS或CIFS共享。因为在这种情况下、如果您尝试扩展磁盘空间、则会使用一些LVM命令、例如 `resize` 和 `extend` 可能无法按预期工作。

====
. 确认 `/opt/netapp/data` 目录所有者(mysql)和组(root)保持不变： `ls -ltr /opt/netapp/ | grep data`
+
系统将返回类似于以下内容的确认消息：

+
[listing]
----
drwxr-xr-x.  17 mysql root  4096 Aug 28 13:08 data
----
. 如果启用了SE Linux、请确认的上下文 `/opt/netapp/data` 目录仍设置为mysqld_db_t：
+
.. `touch /opt/netapp/data/abc`
.. `ls -Z /opt/netapp/data/abc`


+
系统将返回类似于以下内容的确认消息：



[listing]
----
-rw-r--r--. root root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/abc
----
. 删除文件 `abc` 这样、此无关文件将来不发生原因 会出现数据库错误。
. 从复制内容 `backup-data` 返回到展开的 `/opt/netapp/data` 目录： `cp -arp /backup-data/* /opt/netapp/data/`
. 如果启用了 SE Linux ，请运行以下命令： `chcon -R --type=mysqld_db_t /opt/netapp/data`
. 启动 MySQL 服务： `systemctl start mysqld`
. 启动 MySQL 服务后，按所示顺序启动 ocie 和 ocieau 服务： `systemctl start ocie ocieau`
. 启动所有服务后、删除备份文件夹 `/backup-data`： `rm -rf /backup-data`

