---
permalink: api-automation/concept-metrics-apis.html 
sidebar: sidebar 
keywords:  
summary: 'Active IQ Unified Manager 在 /datacenter" 类别下为您提供了一组 API ，可用于查看数据中心中集群和存储对象的性能数据。这些 API 会检索不同存储对象的性能数据，例如集群，节点， LUN ，卷， 聚合和 Storage VM 。' 
---
= 查看性能指标
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager 在下为您提供了一组API `/datacenter` 用于查看数据中心中集群和存储对象的性能数据的类别。这些 API 会检索不同存储对象的性能数据，例如集群，节点， LUN ，卷， 聚合和 Storage VM 。

。 `/metrics` 和 `/analytics` API提供了不同的性能指标视图、使用这些视图、您可以深入了解数据中心中以下存储对象的不同详细信息级别：

* 集群
* nodes
* Storage VM
* 聚合
* volumes
* LUN


下表对进行了比较 `/metrics` 和 `/analytics` API中有关检索到的性能数据的详细信息。

[cols="2*"]
|===
| 指标 | 分析 


 a| 
单个对象的性能详细信息。例如、 `+/datacenter/cluster/clusters/{key}/metrics+` API要求将集群密钥输入为 `path` 用于检索该特定集群的指标的参数。
 a| 
数据中心中多个相同类型对象的性能详细信息。例如、 `/datacenter/cluster/clusters/analytics` API检索数据中心中所有集群的汇总指标。



 a| 
基于检索时间间隔参数的存储对象性能指标示例。
 a| 
特定类型存储对象在特定时间段(超过72小时)内的性能的高级别聚合值。



 a| 
将检索对象的基本详细信息，例如节点或集群的详细信息。
 a| 
未检索到任何特定详细信息。



 a| 
系统会为单个对象检索累积计数器、例如一段时间内的最小、最大和平均性能值、例如读取、写入、总计、和其他计数器。例如、 `+/datacenter/cluster/nodes/{key}/metrics+` API检索节点的以下详细信息(以及其他信息)：

[listing]
----
 {
      "iops": {
        "local": {
          "others": 100.53,
          "read": 100.53,
          "total": 100.53,
          "write": 100.53
        },
        "others": 100.53,
        "read": 100.53,
        "total": 100.53,
        "write": 100.53
      },
      "latency": {
        "others": 100.53,
        "read": 100.53,
        "total": 100.53,
        "write": 100.53
      },
      "performance_capacity": {
        "available_iops_percent": 0,
        "free_percent": 0,
        "system_workload_percent": 0,
        "used_percent": 0,
        "user_workload_percent": 0
      },
      "throughput": {
        "other": 100.53,
        "read": 100.53,
        "total": 100.53,
        "write": 100.53
      },
---- a| 
对于同一类型的所有对象，将显示一个聚合值。例如、 `/datacenter/cluster/nodes/analytics` API检索所有节点的以下值(以及其他值)：

[listing]
----
 {
      "iops": 2757.5723,
      "latency": 0.8266,
      "throughput": 13254.6992,
      "utilization_percent": 58.6488,
      "period": 72,
      "performance_capacity": {
        "used_percent": 63.5317,
        "available_iops_percent": 60731.3086
      },
----


 a| 
时间范围和示例数据基于以下计划：数据的时间范围。示例可以是 1 小时， 12 小时， 1 天， 2 天， 3 天， 15d ， 1 瓦， 1 米， 2 米， 3 米， 6 万。如果范围超过 3 天（ 72 小时），则可以获得 1 小时的样本，否则为 5 分钟的样本。每个时间范围的时间段如下：

* 1 小时：最近一小时的指标在 5 分钟内取样。
* 12h ：最近 12 小时内的指标在 5 分钟内取样。
* 1d ：最近一天的指标取样时间超过 5 分钟。
* 2D ：最近 2 天在 5 分钟内取样的指标。
* 3D ：最近 3 天在 5 分钟内取样的指标。
* 15d ：在 1 小时内取样的最近 15 天的指标。
* 1 瓦：最近一周的指标取样时间超过 1 小时。
* 1M ：最近一个月内的指标，取样时间超过 1 小时。
* 2M ：最近 2 个月内的指标，取样时间为 1 小时。
* 3m ：最近 3 个月内的指标，取样时间为 1 小时。
* 6 米：最近 6 个月内的指标，取样时间为 1 小时。


可用值： 1 小时， 12 小时， 1 天， 2 天， 3 天， 15d ， 1 瓦， 1 米， 2 米， 3 米， 6 万

默认值： 1h
 a| 
超过72小时、即3天。计算此样本的持续时间以 ISO-8601 标准格式表示。

|===
下表介绍了 `/metrics` 和 `/analytics` API详细信息。

[NOTE]
====
例如、这些API返回的IOPS和性能指标是双倍值 `100.53`。不支持使用管道（我们）和通配符（ * ）筛选这些浮点值。

====
[cols="3*"]
|===
| HTTP 动词 | 路径 | Description 


 a| 
`GET`
 a| 
`+/datacenter/cluster/clusters/{key}/metrics+`
 a| 
检索由集群密钥的输入参数指定的集群的性能数据（示例和摘要）。返回的信息包括集群密钥和UUID、时间范围、IOPS、吞吐量和样本数量。



 a| 
`GET`
 a| 
`/datacenter/cluster/clusters/analytics`
 a| 
检索数据中心中所有集群的高级别性能指标。您可以根据所需条件筛选结果。系统将返回聚合 IOPS ，吞吐量和收集时间段（以小时为单位）等值。



 a| 
`GET`
 a| 
`+/datacenter/cluster/nodes/{key}/metrics+`
 a| 
检索由节点密钥的输入参数指定的节点的性能数据（示例和摘要）。返回的信息包括节点 UUID ，时间范围， IOPS 摘要，吞吐量，延迟和性能，收集的样本数量以及利用率百分比。



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes/analytics`
 a| 
检索数据中心中所有节点的高级别性能指标。您可以根据所需条件筛选结果。系统将返回节点和集群密钥等信息以及聚合 IOPS ，吞吐量和收集时间段（以小时为单位）等值。



 a| 
`GET`
 a| 
`+/datacenter/storage/aggregates/{key}/metrics+`
 a| 
检索聚合密钥的输入参数指定的聚合的性能数据（示例和摘要）。返回的信息包括时间范围， IOPS 摘要，延迟，吞吐量和性能容量，为每个计数器收集的样本数以及利用率百分比。



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates/analytics`
 a| 
检索数据中心中所有聚合的高级别性能指标。您可以根据所需条件筛选结果。系统将返回聚合密钥和集群密钥等信息以及聚合 IOPS ，吞吐量和收集时间段（以小时为单位）等值。



 a| 
`GET`
 a| 
`+/datacenter/storage/luns/{key}/metrics+`

`+/datacenter/storage/volumes/{key}/metrics+`
 a| 
检索由 LUN 或卷密钥的输入参数指定的 LUN 或文件共享（卷）的性能数据（示例和摘要）。信息，例如读取，写入和总 IOPS ，延迟和吞吐量的最小值，最大值和平均值摘要， 并返回为每个计数器收集的样本数量。



 a| 
`GET`
 a| 
`/datacenter/storage/luns/analytics`

`/datacenter/storage/volumes/analytics`
 a| 
检索数据中心中所有 LUN 或卷的高级别性能指标。您可以根据所需条件筛选结果。将返回 Storage VM 和集群密钥等信息以及聚合 IOPS ，吞吐量和收集时间段（以小时为单位）等值。



 a| 
`GET`
 a| 
`+/datacenter/svm/svms/{key}/metrics+`
 a| 
检索由 Storage VM 密钥的输入参数指定的 Storage VM 的性能数据（示例和摘要）。基于每个受支持协议的IOPS摘要、例如 `nvmf, fcp, iscsi`，和 `nfs`返回的样本包括吞吐量、延迟和收集的样本数量。



 a| 
`GET`
 a| 
`/datacenter/svm/svms/analytics`
 a| 
检索数据中心中所有 Storage VM 的高级别性能指标。您可以根据所需条件筛选结果。将返回 Storage VM UUID ，聚合 IOPS ，延迟，吞吐量和收集时间段（以小时为单位）等信息。



 a| 
`GET`
 a| 
`/datacenter/cluster/licensing/licenses` `+/datacenter/cluster/licensing/licenses/{key}+`
 a| 
返回数据中心集群上安装的许可证的详细信息。您可以根据所需条件筛选结果。系统将返回许可证密钥、集群密钥、到期日期和许可证范围等信息。您可以输入许可证密钥以检索特定许可证的详细信息。

|===