---
permalink: install-linux/task-upgrading-the-host-os-from-rhel-6-x-to-7-x.html 
sidebar: sidebar 
keywords:  
summary: 如果先前在 Red Hat Enterprise Linux 7.x 系统上安装了 Unified Manager ，但需要升级到 Red Hat Enterprise Linux 8.x ，则必须按照本主题中列出的过程之一进行操作。在这两种情况下，都必须在 Red Hat Enterprise Linux 7.x 系统上创建 Unified Manager 的备份，然后将备份还原到 Red Hat Enterprise Linux 8.x 系统。 
---
= 将主机操作系统从 Red Hat Enterprise Linux 7.x 升级到 8.x
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果先前在 Red Hat Enterprise Linux 7.x 系统上安装了 Unified Manager ，但需要升级到 Red Hat Enterprise Linux 8.x ，则必须按照本主题中列出的过程之一进行操作。在这两种情况下，都必须在 Red Hat Enterprise Linux 7.x 系统上创建 Unified Manager 的备份，然后将备份还原到 Red Hat Enterprise Linux 8.x 系统。



== 关于此任务

下面列出的两个选项之间的区别是，在一种情况下，您要将 Unified Manager 还原到新的 8.x 服务器，而在另一种情况下，您要对同一台服务器执行还原操作。

由于此任务要求您在 Red Hat Enterprise Linux 7.x 系统上创建 Unified Manager 的备份，因此，只有在准备完成整个升级过程时，才应创建备份，以便 Unified Manager 在最短时间内脱机。在关闭 Red Hat Enterprise Linux 7.x 系统以及启动新的 Red Hat Enterprise Linux 8.x 之前的时间段内， Unified Manager UI 中会显示所收集数据的空隙。

如果您需要查看有关备份和还原过程的详细说明，请参见 _RAID Active IQ Unified Manager 联机帮助。

* 使用新服务器升级主机操作系统 *

如果您的备用系统可以安装 Red Hat Enterprise Linux 8.x 软件，以便在 Red Hat Enterprise Linux 7.x 系统仍然可用时在该系统上执行 Unified Manager 还原，请按照以下步骤进行操作。

. 使用 Red Hat Enterprise Linux 8.x 软件安装和配置新服务器。
+
xref:reference-red-hat-and-centos-software-and-installation-requirements.adoc[Red Hat 软件和安装要求]

. 在 Red Hat Enterprise Linux 8.x 系统上，安装与现有 Red Hat Enterprise Linux 7.x 系统上相同版本的 Unified Manager 软件。
+
xref:concept-installing-unified-manager-on-rhel-or-centos.adoc[在 Red Hat Enterprise Linux 上安装 Unified Manager]

+
安装完成后，请勿启动 UI 或配置任何集群，用户或身份验证设置。备份文件会在还原过程中填充此信息。

. 在Red Hat Enterprise Linux 7.x系统上、从Web UI的管理菜单中创建Unified Manager备份、然后复制备份文件 (`.7z` file)和数据库存储库目录的内容 (`/database-dumps-repo` 子目录)到外部位置。
. 在 Red Hat Enterprise Linux 7.x 系统上，关闭 Unified Manager 。
. 在Red Hat Enterprise Linux 8.x系统上、复制备份文件 (`.7z` 文件)从外部位置到 `/opt/netapp/data/ocum-backup/` 和数据库存储库文件 `/database-dumps-repo` 下的子目录 `/ocum-backup` 目录。
. 输入以下命令从备份文件还原 Unified Manager 数据库： `um backup restore -f /opt/netapp/data/ocum-backup/<backup_file_name>`
. 在 Web 浏览器中输入 IP 地址或 URL 以启动 Unified Manager Web UI ，然后登录到系统。


确认系统运行正常后，您可以从 Red Hat Enterprise Linux 7.x 系统中删除 Unified Manager 。

* 升级同一服务器上的主机操作系统 *

如果您没有可安装 Red Hat Enterprise Linux 8.x 软件的备用系统，请按照以下步骤进行操作。

. 从Web UI的管理菜单中、创建Unified Manager备份、然后复制备份文件 (`.7z` file)和数据库存储库目录的内容 (`/database-dumps-repo` 子目录)到外部位置。
. 从系统中删除 Red Hat Enterprise Linux 7.x 映像，然后彻底擦除系统。
. 在同一系统上安装和配置 Red Hat Enterprise Linux 8.x 软件。
+
xref:reference-red-hat-and-centos-software-and-installation-requirements.adoc[Red Hat 软件和安装要求]

. 在 Red Hat Enterprise Linux 8.x 系统上，安装与 Red Hat Enterprise Linux 7.x 系统上相同版本的 Unified Manager 软件。
+
xref:concept-installing-unified-manager-on-rhel-or-centos.adoc[在 Red Hat Enterprise Linux 上安装 Unified Manager]

+
安装完成后，请勿启动 UI 或配置任何集群，用户或身份验证设置。备份文件会在还原过程中填充此信息。

. 复制备份文件 (`.7z` 文件)从外部位置到 `/opt/netapp/data/ocum-backup/` 和数据库存储库文件 `/database-dumps-repo` 下的子目录 `/ocum-backup` 目录。
. 输入以下命令从备份文件还原 Unified Manager 数据库：``um backup restore -f /opt/netapp/data/ocum-backup/<backup_file_name>``
. 在 Web 浏览器中输入 IP 地址或 URL 以启动 Unified Manager Web UI ，然后登录到系统。

